### ISSUE TITLE
Provide play-services-free build flavor

### ISSUE THREAD

**Issue by krt16s** [Etuldan/spaRSS#1]
Google's play-services are a non-free dependency which we at FDroid cannot use. Since it looks like they are actually just for the wear integration used, it should be easy to provide two build flavors, one building a full-floss version and the other using play-services.

We had patches for flym, but they don't apply anymore and actually it's not something that should be maintained on our side, but in upstream.

**Comment by Etuldan** [comment]
Thank you for the report.
I'll look into this issue, and publish 2 builds, as you said (one with wear support, one without it)
About patches that you made for flym, are they available somewhere ?

**Comment by krt16s** [comment]
Patches: https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/net.fred.feedex/

**Comment by Etuldan** [comment]
When built with AndroidStudio, there are 2 flavors now. One is floss, w/o any GPlay lib.

**Comment by krt16s** [comment]
Do you really want to keep two package ids? Imho it's more like one app/package id in different versions. But it's your call, whatever suits you.

**Comment by Etuldan** [comment]
At the moment, yes, the 2 flavors are quite the same builds. 
But I don't see any disadvantage to have 2 packageID.

**Comment by krt16s** [comment]
No disadvantage, just wanted to make sure. There is no "at the moment".  Once published -- I am pushing to fdroid now -- you cannot go back*.

*) The only somewhat sensible way to change package id is: Release a last build that prompts the user with information, that the package will change. It cannot be forced, since for android, two package ids mean that they are different apps.

**Comment by Etuldan** [comment]
I know that I cannot go back once the packageID is deployed.

You can push it with the packageID "net.etuldan.sparss.floss" ;)
