### ISSUE TITLE
New new entries button is buggy, worthless and looks really wrong (solution inside)

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#105]
@Etuldan :

No offence, but, the new new read entries button (the bell icon with the counter), which was introduced in version 1.10.3, looks incredibly ugly and out of place.

First of all, the icon is not only bigger in size than the other icons, it's also variable in size which looks very buggy, see following screenshots:

![Image](https://cloud.githubusercontent.com/assets/7558360/10460744/10f5791a-71d6-11e5-8ef3-e8a80429a970.png)
![Image](https://cloud.githubusercontent.com/assets/7558360/10460746/1419e9d2-71d6-11e5-8627-a29fd4a9dd62.png)

As you can see, the counter also does not fit the icon, it exceeds the icon size.

I am wondering:

1.

Why do we need a new entries counter?

If there are new entries, then I don't really care how many new entries there are. I'd rather care about how many unread entries there are.

You could put the unread count in the title of the action bar.

So, let's say there are 100 unread entries for example. Then the title of the action bar would be:

> Entries (100)

If there are 50 unread entries, then the title of the action bar would be:

> Entries (50)

and so on...

2.

Why do we need a button to show new entries?

Actually I think it's really annoying to always have to press that button to make the new entries show up in the entries list.

This button is absolutely worthless when thinking about it (IMHO)!

It would be much better if new entries would immediately land in the entries list without having to press such an annoying button first.

So:

Could you please remove the new entries button and new entries count and instead make the action bar title show the unread count and make new entries show up in the entries list immediately?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
Related:

https://github.com/Etuldan/spaRSS/issues/66

**Comment by nk404** [comment]
I can confirm this. Please remove this button or allow user to enable/disable it and use some logical metaphors for it like white bell for no notifications and white bell with yellow/cyan circle, on top left, for more than 0 new articles etc.

**Comment by Etuldan** [comment]
1. We don't need a counter. I'll remove it
2. We need a button to display new entries (or customisable). Some people prefer to read all the 'previous' feed, then mark them ad read, and then display the new ones.

So, I think I:
will remove the counter.
modify the icon of this button.
perhaps make it optional (like the mark all as read one)

What I need ATM is to find/create a better icon for it.

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> So, I think I:
> will remove the counter.

Yes, please, that would make sense.

> @Etuldan wrote:
> 
> modify the icon of this button.
> perhaps make it optional (like the mark all as read one)

Yes, please make the button optional. The button is so annoying! And it would also solve https://github.com/Etuldan/spaRSS/issues/66.

> @Etuldan wrote:
> 
> What I need ATM is to find/create a better icon for it.

I had a look at the Google Material icons:

If there are no new entries, then you could use the following Material icon for the button:

[ic_exposure_zero](https://www.google.com/design/icons/#ic_exposure_zero)

As soon as there are new entries, you could make the button change to the following icon:

[ic_plus_one](https://www.google.com/design/icons/#ic_plus_one)
or:
[ic_new_releases](https://www.google.com/design/icons/#ic_new_releases)
or:
[ic_file_download](https://www.google.com/design/icons/#ic_file_download)
or:
[ic_expand_more](https://www.google.com/design/icons/#ic_expand_more)

Or, alternatively, you could use only:

[ic_new_releases](https://www.google.com/design/icons/#ic_new_releases)
or:
[ic_file_download](https://www.google.com/design/icons/#ic_file_download)
or:
[ic_expand_more](https://www.google.com/design/icons/#ic_expand_more)

and reduce the opacity of the icon (i.e. showing it as inactive) when there are no new entries and make it have full opacity (i.e. showing it as active) once there are new entries. The Google Material Design Guidelines tell you how to deal with active and inactive icons, see the bottom ("Color" section) of the following system icons page:

https://www.google.com/design/spec/style/icons.html#icons-system-icons

What do you think?

Regards

**Comment by Etuldan** [comment]
If the button is optional, and disable in the user setting, when doe the list should be updated ?
When opening / bring thge app to front, I think it's always.
When clicking on the "refresh" button, I think also to do it
But when the app is displayed, and at the same time, the feed are uploaded automaticaly (w/o pressing the button), what should I do ?

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> But when the app is displayed, and at the same time, the feed are uploaded automaticaly (w/o pressing the button), what should I do ?

How about:

Update the list immediately and keep staying at the current scroll position while updating (i.e. do not automatically jump to the top of the list while updating).

That way, if a user would be reading/scrolling through the list, he would not be distracted from feed updates.

Would that be possible?

If that would be possible, I think it should also be done like that when pressing the refresh button.

Regards

**Comment by nk404** [comment]
May i ask what was the issue with previous behaviour where we got colored square notifying us that there are new articles?

**Comment by wp9015362** [comment]
> @nk404 wrote:
> 
> May i ask what was the issue with previous behaviour where we got colored square notifying us that there are new articles?

See:

https://github.com/Etuldan/spaRSS/issues/67

Regards

**Comment by wp9015362** [comment]
@Etuldan :

I see with version 1.10.4 you have changed the icon to [ic_new_releases](https://www.google.com/design/icons/#ic_new_releases).

That looks much better than the previous icon.

But the [ic_new_releases](https://www.google.com/design/icons/#ic_new_releases) icon always has full opacity (i.e. it always looks active), so you can't really tell if there are new entries or not.

Could you please reduce the opacity of the icon (i.e. showing it as inactive) when there are no new entries and make it have full opacity (i.e. showing it as active) once there are new entries?

That way it would be possible to see if there are new entries or not.

The Google Material Design Guidelines tell you how to deal with active and inactive icons, see the bottom ("Color" section) of the following system icons page:

https://www.google.com/design/spec/style/icons.html#icons-system-icons

Alternatively you could also make the icon disappear when there are no new entries and make it appear once there are new entries.

Regards

**Comment by Foxdelmar** [comment]
nice ongoing discussion.

1.) I liked the counter to know how many new articles need to be read soon.
2.) I could live without that counter when the counter of all unread articles is always shown in the menü. (as requested in another issue)
3.) Please change the appeareance of the button in the right corner. 
-> Please change the appereance, after I tap the button. Then all new items should be added in the list AND the button should change. (as proposed above)
-> Show a text pop up if I tap the button but no loaded new articles are available that tell the user why nothing. Otherwise no new users will understand that button easily.

Thanks for your work on this app! 
It is great to have an eager maintainer :)

**Comment by Etuldan** [comment]
Should be fixed (new build soon).

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> Should be fixed (new build soon).

Where is the option to disable the new entries button?

I can't find it in the new build.

Regards

**Comment by Etuldan** [comment]
I consider this issue only related to the "Show unread button" in the ActionBar.
The title bar and settings option is another issue ;)
Title bar : #121 
Settings : #66
