### ISSUE TITLE
Please put unread count in title of action bar

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#109]
@Etuldan :

I had already requested this as part of https://github.com/Etuldan/spaRSS/issues/105, but I think it makes sense to open a separate issue for it, so:

Could you please put the unread count in the title of the action bar?

So, let's say there are 100 unread entries for example. Then the title of the action bar would be:

> Entries (100)

If there are 50 unread entries, then the title of the action bar would be:

> Entries (50)

and so on...

Regards

**Comment by Foxdelmar** [comment]
+1

**Comment by revuwa** [comment]
Such a feature would be really great.
(I bloody missing that counter since the latest version v1.10.4 dropped it)...

**Comment by Etuldan** [comment]
Should be fixed (new build soon).
