### ISSUE TITLE
Refresh animation doesn't stop

### ISSUE THREAD

**Issue by KAMiKAZOW** [Etuldan/spaRSS#11]
When manually refreshing feeds, the loading animation doesn't stop once it's done. Works fine in Flym.

**Comment by Etuldan** [comment]
Do you have a particular feed on which it occurs ? (on my feed list, there is no issue about loading animation on manual refresh

**Comment by KAMiKAZOW** [comment]
I just tapped the Refresh All button. I also have "Retrieve full text" enabled for all feeds.

**Comment by Etuldan** [comment]
Can you export your list (in OPML format) and send it to me ? (feel free to private message/email me if you don't wan't to make your list public)

**Comment by KAMiKAZOW** [comment]
That list is not so interesting 😉

<?xml version='1.0' encoding='utf-8'?>
<opml version='1.1'>
<head>
<title>Flym export</title>
<dateCreated>1432066186594</dateCreated>
</head>
<body>
	<outline title='Golem.de' type='rss' xmlUrl='http://rss.golem.de/rss.php?feed=ATOM1.0' retrieveFullText='true'/>
	<outline title='heise open news' type='rss' xmlUrl='http://www.heise.de/open/news/news-atom.xml' retrieveFullText='true'/>
	<outline title='Phoronix' type='rss' xmlUrl='http://feedproxy.google.com/Phoronix' retrieveFullText='true'/>
	<outline title='Planet KDE' type='rss' xmlUrl='http://planetkde.org/rss20.xml' retrieveFullText='false'/>
	<outline title='Fedora Magazine' type='rss' xmlUrl='http://fedoramagazine.org/feed/' retrieveFullText='false'/>
	<outline title='IFLScience' type='rss' xmlUrl='http://www.iflscience.com/rss.xml' retrieveFullText='true'/>
</body>
</opml>

**Comment by KAMiKAZOW** [comment]
Weird. Now I tried it again and it works…

**Comment by Etuldan** [comment]
Thank you for the list.
I'll be able to inspect the issue on saturday (However, I'll try to reproduce before)

About the OPML export, i'll also look into the issue.

**Comment by Etuldan** [comment]
Indeed, with you feed list, the waiting animation is 'very' long (about 5 minutes on a Wifi network) , but stops.

The time to retrieve the news list and short description is quite fast, but the app then retrieve all content, and this time depends of the length or articles, the quality of your Internet connexion, and so on.

Can you confirm that the waiting animation stops after waiting a while ?

**Comment by KAMiKAZOW** [comment]
I'm looking at the main screen for 12 minutes now and the refresh animation is still ongoing. IMO at some point it should just have timed out.

**Comment by KAMiKAZOW** [comment]
21 minutes. I'm going to kill the app now.

**Comment by ildar** [comment]
Guess you could check what's going on in a adb logcat

-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by KAMiKAZOW** [comment]
OK, turns out the animation is not only a visual inconvenience, all that content fetching brains battery like crazy.
If a feed/website is broken or so and spaRSS can't fetch the stuff in a timely manner, it should just timeout.

**Comment by Etuldan** [comment]
Issue seems to be related to the feed http://planetkde.org/rss20.xml
I'll try to debug it, meanwhile, if you want to use spaRSS w/o battery drain, you can disable this feed.

**Comment by KAMiKAZOW** [comment]
I enabled to prefetch images when using Wi-Fi, btw

**Comment by Etuldan** [comment]
Temp Fix in the experimental branch.
Tell me if you have the environment to build the APK (I could build it for you if you want) in order to check if the fix (dirty-fix) works for you.

**Comment by KAMiKAZOW** [comment]
An APK by you would be nice.

**Comment by Etuldan** [comment]
For information, the ItemFeed that is problematic is:


    <item>
      <guid isPermaLink="false">tag:blogger.com,1999:blog-3089927661720252822.post-1758360254213612755</guid>
      <title>Getting started!</title>
      <author>Marius Stanciu (stancium)</author>
      <pubDate>Mon, 01 Jun 2015 14:47:04 GMT</pubDate>
      <link>http://mariusoc.blogspot.com/2015/05/getting-started.html</link>
      <description>&lt;p&gt;How about that!? Google Summer of Code coding period started ( quite a while ago though ) and I thought I'd share some of my enthusiasm with you!&lt;br /&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;Firstly, impression about the program itself:&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;From what I've seen so far, the best part is definitely having the chance to code along with such great people, while getting precious feedback. This is what I've lacked so far in my experience as a student, and it certainly is the best way to get introduced to open-source software ( especially KDE :D ).&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;Now about the project:&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;My work this summer will revolve around offering OpenStreetMap( OSM ) support to Marble: this will involve offering the user a complete experience: from opening OSM files, to viewing and editing them, to finally exporting them in ".osm" files.&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;Some of the work is already done, yet it still requires some tweaking, some technical bits will involve some code refactoring, and some parts( the most exciting ones ) consist of creating specialized tools for the map editor.&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;Here's a sample to give you an idea of what interesting stuff I'm working on:&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;(Mock-up on what editing OSM relations might look like)&lt;br /&gt;&lt;br /&gt;&lt;div class="separator" style="clear: both; text-align: center;"&gt;&lt;a href="http://1.bp.blogspot.com/-C9Hg66ntLv4/VWtod-ViAXI/AAAAAAAAAA8/5ZcnAL-KIww/s1600/relation_2.png" style="clear: left; float: left; margin-bottom: 1em; margin-right: 1em;"&gt;&lt;table cellpadding="0" cellspacing="0" class="tr-caption-container" style="float: left; margin-right: 1em; text-align: left;"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style="text-align: center;"&gt;&lt;a href="http://3.bp.blogspot.com/--JzTJZDgAng/VWtobVVwJII/AAAAAAAAAA0/6L44RRY0htI/s1600/bus%2BRoute%2B2.png" style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;"&gt;&lt;img border="0" height="266" src="http://3.bp.blogspot.com/--JzTJZDgAng/VWtobVVwJII/AAAAAAAAAA0/6L44RRY0htI/s320/bus%2BRoute%2B2.png" width="320" /&gt;&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class="tr-caption" style="text-align: center;"&gt;Selecting nodes and ways&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/a&gt;&lt;/div&gt;&lt;br /&gt;&lt;table align="center" cellpadding="0" cellspacing="0" class="tr-caption-container" style="float: left; margin-right: 1em; text-align: left;"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style="text-align: center;"&gt;&lt;a href="https://1.bp.blogspot.com/-C9Hg66ntLv4/VWtod-ViAXI/AAAAAAAAAA8/5ZcnAL-KIww/s1600/relation_2.png" style="margin-left: auto; margin-right: auto;"&gt;&lt;img border="0" height="170" src="http://1.bp.blogspot.com/-C9Hg66ntLv4/VWtod-ViAXI/AAAAAAAAAA8/5ZcnAL-KIww/s320/relation_2.png" width="320" /&gt;&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class="tr-caption" style="text-align: center;"&gt;Adding them to a relation&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;table cellpadding="0" cellspacing="0" class="tr-caption-container" style="float: left; margin-right: 1em; text-align: left;"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style="text-align: center;"&gt;&lt;a href="http://1.bp.blogspot.com/-VKXfODMlnFY/VWtofcLuz3I/AAAAAAAAABE/WpbrxfS-Q7c/s1600/relation_1.png" style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;"&gt;&lt;img border="0" height="179" src="http://1.bp.blogspot.com/-VKXfODMlnFY/VWtofcLuz3I/AAAAAAAAABE/WpbrxfS-Q7c/s320/relation_1.png" width="320" /&gt;&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td class="tr-caption" style="text-align: center;"&gt;Settings tags for that relation&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Well, that's all folks! I hope I've passed some of my enthusiasm, and if that's the case, stay tuned for my progress along the summer, as I'll be posting more :D&lt;/div&gt;</description>
    </item>

**Comment by Etuldan** [comment]
https://github.com/Etuldan/spaRSS/releases/tag/v1.10-alpha2

**Comment by KAMiKAZOW** [comment]
Initial testing looks good. Thank you very much!
