### ISSUE TITLE
[Help] Show new entries without button click

### ISSUE THREAD

**Issue by mrfanatic** [Etuldan/spaRSS#112]
I've been trying to solve this for days now and currently can't make it work. Does anyone got a clues on how to make this work?

**Comment by wp9015362** [comment]
@mrfanatic :

Please search for existing issues the next time before you submit an issue here.

This is already being worked on, see the following two issues:

https://github.com/Etuldan/spaRSS/issues/66
https://github.com/Etuldan/spaRSS/issues/105

Regards

**Comment by mrfanatic** [comment]
oh, sorry for being an a** :)
