### ISSUE TITLE
Accept Invalid SSL Certificates

### ISSUE THREAD

**Issue by anoadragon453** [Etuldan/spaRSS#115]
Upon trying to load a feed with a self-signed certificate I am presented with this error just under the feed URL:

java.security.cert.certPathVali...

This feed is coming from my own OwnCloud instance that uses a self-signed certificate. In the meantime before Let's Encrypt gets rolling and I can get a proper cert, it would be nice to be able to view my RSS feed on-device.

Thanks.

**Comment by toyotabedzrock** [comment]
You could just copy over the certificate to your device so it would be trusted. That is the proper solution if it is just for your usage.

**Comment by eighthave** [comment]
Go get yourself a free, real certificate: https://letsencrypt.org/

No need to break the security of this app.  :)

**Comment by anoadragon453** [comment]
I have since done so and it's working fine. I only asked as a few other applications allowed the option. 

Hey, maybe it'll push more people to encrypt.

**Comment by eighthave** [comment]
Excellent :)

No problem with asking.  HTTPS is definitely a painful protocol to deal
with.  But allowing broken HTTPS leaves us with broken HTTPS, which is
very bad in the long run.  Such an option seems like a simple solution,
but https://letsencrypt.org or another CA is really the way to go here.
