### ISSUE TITLE
Why spaRSS ?

### ISSUE THREAD

**Issue by sbaconnais** [Etuldan/spaRSS#117]
First of all, I'm not starting an argument nor  criticizing.

I genuinely would like to know the differences between Flym and spaRSS (I already saw graphical differences) and to know why it is a fork instead of a contribution.

I also think you should explain it in the readme file.

Thanks :)

**Comment by Etuldan** [comment]
This : https://github.com/FredJul/Flym/pull/296 :)

**Comment by sbaconnais** [comment]
That's indeed a very good reason :)

I insist on the fact that you should explain it clearly on your github.

Keep the good work ! :)

**Comment by survietamine** [comment]
hello, thanks for the explanation. I'm very interested in this app and will try to contribute as a tester.

**Comment by Etuldan** [comment]
See Readme on frontpage.
Thanks for the idea :)
