### ISSUE TITLE
How to delete ic_edit in drawble ?

### ISSUE THREAD

**Issue by ullahchozta** [Etuldan/spaRSS#120]
How to delete menu ic_edit in drawble ?

**Comment by Etuldan** [comment]
Why do you want to delete it ?
If you want to, you have to delete the png file in all drawable-* folders, then remove any reference to it in all the xml files. (otherwise, it might not compile)

**Comment by ullahchozta** [comment]
i want to delete featured..where is i can delete the code ?

**Comment by Etuldan** [comment]
What is the point about editing it ?
You/Users will still be able to delete and create new one, even if you delete the feature.

**Comment by ullahchozta** [comment]
i want to delete that featured because my project already feed default.. so, i want delete it

**Comment by mrfanatic** [comment]
You have a default feed, so you don't want users to edit the feed, right?
go to `mobile/src/main/res/layout/view_drawer_content.xml`
and simply comment the Edit feed ImageButton like below :)
```javascript
<!--ImageButton
            style="?android:attr/buttonBarButtonStyle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:onClick="onClickEditFeeds"
            android:src="@drawable/ic_edit"/-->
```

**Comment by ullahchozta** [comment]
ok thank u
