### ISSUE TITLE
[fc] crash on rotations

### ISSUE THREAD

**Issue by revuwa** [Etuldan/spaRSS#127]
Because of this issue: https://github.com/Etuldan/spaRSS/issues/121 I tried to rotate the app while loading/searching for new entries. I hoped to see the number of new entries in landscape mode:
![landscape](https://cloud.githubusercontent.com/assets/7300276/11380685/e987cfd4-92f7-11e5-8bbd-823c173e251d.png)
But, the app crashed while loading. So I thought, I have to wait until the refresh process is finished, but the app crashes on switching to landscape mode, again.
I tried this several times. Sometimes the app didn't crash on switching to landscape, but finally on switching back to portrait mode.

I've logged 3 procedures:
* crash while refreshing/loading and switching to landscape
* crash after finished refreshing and switching to landscape
* crash after switching to landscape successfully, and crashes after switching back to portrait

The part I've seen in all of this logs is:

| PID|	Event|	Tag|		Message |
| ------------- | ------------- | ------------- | ------------- |
|8570	|D	|AndroidRuntime	|Shutting down VM|
|8570	|W	|dalvikvm	|threadid=1: thread exiting with uncaught exception (group=0x415a1930)|
|8570	|E	|AndroidRuntime	|FATAL EXCEPTION: main|
|8570	|E	|AndroidRuntime	|java.lang.NullPointerException|
|8570	|E	|AndroidRuntime	|	at net.etuldan.sparss.fragment.EntriesListFragment$3.a(SourceFile:145)|
|8570	|E	|AndroidRuntime	|	at net.etuldan.sparss.fragment.EntriesListFragment$3.onLoadFinished(SourceFile:122)|
|8570	|E	|AndroidRuntime	|	at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)|
|8570	|E	|AndroidRuntime	|	at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)|
|8570	|E	|AndroidRuntime	|	at android.content.Loader.deliverResult(Loader.java:143)|
|8570	|E	|AndroidRuntime	|	at android.content.CursorLoader.deliverResult(CursorLoader.java:113)|
|8570	|E	|AndroidRuntime	|	at android.content.CursorLoader.deliverResult(CursorLoader.java:43)|
|8570	|E	|AndroidRuntime	|	at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:254)|
|8570	|E	|AndroidRuntime	|	at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:91)|
|8570	|E	|AndroidRuntime	|	at android.os.AsyncTask.finish(AsyncTask.java:631)|
|8570	|E	|AndroidRuntime	|	at android.os.AsyncTask.access$600(AsyncTask.java:177)|
|8570	|E	|AndroidRuntime	|	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)|
|8570	|E	|AndroidRuntime	|	at android.os.Handler.dispatchMessage(Handler.java:99)|
|8570	|E	|AndroidRuntime	|	at android.os.Looper.loop(Looper.java:137)|
|8570	|E	|AndroidRuntime	|	at android.app.ActivityThread.main(ActivityThread.java:5227)|
|8570	|E	|AndroidRuntime	|	at java.lang.reflect.Method.invokeNative(Native Method)|
|8570	|E	|AndroidRuntime	|	at java.lang.reflect.Method.invoke(Method.java:511)|
|8570	|E	|AndroidRuntime	|	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)|
|8570	|E	|AndroidRuntime	|	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)|
|8570	|E	|AndroidRuntime	|	at dalvik.system.NativeStart.main(Native Method)|
|2900	|W	|ActivityManager|	  Force finishing activity net.etuldan.sparss.floss/net.etuldan.sparss.activity.HomeActivity|
|2900	|W	|ActivityManager|	Activity pause timeout for ActivityRecord{418f3950 u0 net.etuldan.sparss.floss/net.etuldan.sparss.activity.HomeActivity}|

It would be great if you could have look into this, sometime.
(In case you need more logs, or more parts of the existing logs, please just let me know).

My OS is AOSP 4.2.2 on an i9100 device.
Thanks in advance for any help and/or support.

**Comment by Etuldan** [comment]
May be fixed : see https://github.com/Etuldan/spaRSS/commit/9fc4f7b0d82b6615c94954a3715765e3b3213aa7
Reopen it if still present ;)

**Comment by revuwa** [comment]
> May be fixed : see 9fc4f7b
> Reopen it if still present ;)

Thanks for looking into this, but sadly it seems to be still present in the latest version (v1.11.2) :'(

**Comment by Etuldan** [comment]
May be 'already' fixed in git https://github.com/Etuldan/spaRSS/commit/b193251628df7e97a7977ce9eb82f7b0cd922886 , so in the next release.
