### ISSUE TITLE
Can’t process feeds since 1.11.0 update.

### ISSUE THREAD

**Issue by Pwney** [Etuldan/spaRSS#131]
Hello.

Since the 1.11.0 update, spaRSS can’t refresh the feeds (neither auto nor manual). For each feed, it says “Error: The feed can not be processed.”

I rebooted the device and cleared the spaRSS cache but nothing changes.

Nexus 7 (grouper), OmniRom 4.4.4.

**Comment by Etuldan** [comment]
I'm aware of it, but I'll be able to look into only on evening (sorry for this :/)
You can try to backup your feed list, then, remove and reinstall spaRSS, it should work.

**Comment by Etuldan** [comment]
Could you check with the prerelease here https://github.com/Etuldan/spaRSS/releases/tag/1.11.1 ?

**Comment by ilf** [comment]
Same error here. Also downgrading didn't work in F-Droid and after uninstall/reinstall/restore-data-with-Titanium-Backup, 1.10.5 crashes on start. On 1.11.0 now, but unable to use the core function. Please push a new version soon. Thanks!

**Comment by Etuldan** [comment]
Already pushed à new version on PlayStore (Google), should be soon in FDroid.
If not, I'll anyway work on this issue (fix and reimplementing HTTPAuth) today evening.

You can try to backup your feed list as OPML, remove spaRSS (app and data), then reinstall it (so, without data), and import the OPML file.

**Comment by paulle** [comment]
can confirm the issue since the 1.11.0 update.

**Comment by pkra** [comment]
@Etuldan just wanted to say thank you for the quick fix!

**Comment by Etuldan** [comment]
FDroid has now the working one (1.11.2) version : https://f-droid.org/repository/browse/?fdfilter=sparss&fdid=net.etuldan.sparss.floss
Update your repo, then update spaRSS in FDroid ;)
