### ISSUE TITLE
1.11.0 from f-droid isn't able to refresh on my phone

### ISSUE THREAD

**Issue by bet** [Etuldan/spaRSS#133]
Nexus 5 running stock Marshmallow, as soon as I updated SpaRSS and tried to refresh my feeds, every one says 

Error: Attempt to invoke virtual met...

(it truncates there). 

I was running NetGuard, thought it might be that, though I've been running it without problems for a while, confirmed that I had SpaRSS enabled, tried disabling NetGuard entirely, and that didn't fix it.

**Comment by Etuldan** [comment]
Duplicated #131 
Fixed on git,, Updated on PlayStore, will be updated soon on FDroid 

(and It's not a NetGuard issue ;) )

**Comment by bet** [comment]
Thanks! Didn't see an open issue for it when I filed mine, perhaps 131 was closed before I got to github.com. Sorry for the noise.
