### ISSUE TITLE
After update to 1.11.0 feeds stopped working (with workaround)

### ISSUE THREAD

**Issue by nehrwert** [Etuldan/spaRSS#135]
I'm sorry that I have to write so soon again. But after update to 1.11.0 feeds stopped working for me.  In the feed list the message "Error: Attempt to invoke virtual meth..." and then I can't read it any further. 
Ok, while I tried to read the full error message, I opened the feed edit window. Each feed started working again, after I opened and closed the edit window.

Thanks for all your work!

**Comment by Etuldan** [comment]
https://github.com/Etuldan/spaRSS/issues/131

**Comment by nehrwert** [comment]
That was fast! Also sorry I that overlooked the other thread
