### ISSUE TITLE
No feeds working since update to version 1.11.0 (F-Droid build)

### ISSUE THREAD

**Issue by ds33** [Etuldan/spaRSS#136]
Since I updated to version 1.11.0 yesterday none of my feeds claim to have new articles. I have it set to only update automatically over wifi, but hitting refresh is not updating anything or producing errors, nor is refresh on open or timed update. Unchecking the wifi only option doesn't seem to change this either.

Is there some new option I need to change or am I the only one with this problem?

**Comment by Etuldan** [comment]
https://github.com/Etuldan/spaRSS/issues/131

**Comment by ds33** [comment]
Sorry I didn't think to look at the closed issues list.
Thanks.
