### ISSUE TITLE
Feed filter needs to be documented better

### ISSUE THREAD

**Issue by blindbox** [Etuldan/spaRSS#143]
Currently, there's no description on how the filter works. Is it based on ACL? Are all feeds accepted by default if there's no filter? Are all feeds disabled by default if there's no filter?

I had to look into the code to find out how the algorithm works.
I suggest putting a help button next to the + button on the filter page and a small guide on how it works, like this. The text might be something like this (I suck at non-programmer speak so this is probably the wrong way to lay it out to the end user) :-

1. All feed entries are accepted by default.
2. ACCEPT filters will override REJECT filter.
3. So, put one REJECT filter that rejects all entry by clicking regex and putting .* as the entry. If not, your ACCEPT filter will not do anything.

**Comment by Etuldan** [comment]
To be honest, I don't know either.
I forked Flym, but I don't use the filters. Of course, the feature is still present, as it used by some users.

You dig in the code to understand it, and summarize it, thank you :)
Now, we need a 'non-programmer speak', as you said, as I suck also for this.

Thank you also for the idea to add an help button.

**Comment by blindbox** [comment]
Oh, all right. I'll try work on this then. I can't promise anything (might be my first commit on github, whee), but it shouldn't be too much work.

Thinking of attaching a link to the button, so that the explanation could be much longer, have pictures, and make coding even easier for me.

For reference, the filter algorithm is located at:-
[spaRSS/mobile/src/main/java/net/etuldan/sparss/parser/RssAtomParser.java](https://github.com/Etuldan/spaRSS/blob/master/mobile/src/main/java/net/etuldan/sparss/parser/RssAtomParser.java)
Find this method
`        public boolean isEntryFiltered(String title, String content) {`

**Comment by blindbox** [comment]
Good news! Adding that button is easier than I thought. It looks like this:-
![capture](https://cloud.githubusercontent.com/assets/2274992/11659067/3f81847a-9e01-11e5-9661-bbd7a34b6534.PNG)

Now, the only thing left is to write the document. Any idea where I could write it? There's no wiki on this repo.

**Comment by Etuldan** [comment]
Hmm, what I said is that I'll add the button, anyway, you did it, great :)
It's 'only' about the text, that I'll need help :p

Wiki added : https://github.com/Etuldan/spaRSS/wiki

**Comment by Etuldan** [comment]
I'll switch the "Filter Help" text for an help icon ( https://www.google.com/design/icons/#ic_help ).

**Comment by blindbox** [comment]
Sure, go right ahead.
