### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by Ol-li** [Etuldan/spaRSS#145]
http://www.oora.de/startseite/feed.rss

**Comment by Etuldan** [comment]
Not reproduced on my device, do you still have the issue ?
If yes, what is the problem, no article ?

**Comment by Ol-li** [comment]
Yes, no entry. I'm running the official relase 1.11.2  from play store.

**Comment by LukeOwncloud** [comment]
This feed uses uncommon HTTP redirect response code 307. This could help:

    diff --git a/mobile/src/main/java/net/etuldan/sparss/utils/NetworkUtils.java b/mobile/src/main/java/net/etuldan/sparss/utils/NetworkUtils.java
    index 2cebbe5..1a2644f 100755
    --- a/mobile/src/main/java/net/etuldan/sparss/utils/NetworkUtils.java
    +++ b/mobile/src/main/java/net/etuldan/sparss/utils/NetworkUtils.java
    @@ -64,6 +65,9 @@ import java.util.regex.Pattern;
         private static final String FILE_FAVICON = "/favicon.ico";
         private static final String PROTOCOL_SEPARATOR = "://";

    +    /* used e.g. by http://www.oora.de/startseite/feed.rss */
    +    public static final int HTTP_REDIRECT_TEMP = 307;
    +
         private static final CookieManager COOKIE_MANAGER = new CookieManager() {{
             CookieHandler.setDefault(this);
         }};
    @@ -279,7 +285,7 @@ import java.util.regex.Pattern;
             CookieHandler.setDefault(cookieManager);
             int status = 0;
             boolean first = true;
    -        while(first || status == HttpURLConnection.HTTP_MOVED_TEMP || status == HttpURLConnection.HTTP_MOVED_PERM || status == HttpURLConnection.HTTP_SEE_OTHER) {
    +        while(first || status == HttpURLConnection.HTTP_MOVED_TEMP || status == HttpURLConnection.HTTP_MOVED_PERM || status == HttpURLConnection.HTTP_SEE_OTHER || status == HTTP_REDIRECT_TEMP) {
                 if(!first) {
                     url = new URL(connection.getHeaderField("Location"));
                 } else {
