### ISSUE TITLE
Full Content

### ISSUE THREAD

**Issue by Tobias2** [Etuldan/spaRSS#153]
Full content of a feed is often not shown downloaded. 
It is marked in the options but it does not work. 
a few days old feeds are downloaded completely. 
This is version 1.11.3
I think up to version 1.11.0 everything was fine.

**Comment by ildar** [comment]
spaRSS might get interrupted during the update. Then I suggest it skips
downloading the items it already has. If you are to investigate, then you
could check the adb log

**Comment by Tobias2** [comment]
Thank you for your reply. 
Indeed.. a good work around is not to activate the option to reload feeds while opening. 
Do not disturbe the app while updating. 
Then everything works fine. 
Thank you very much that I can use the app fia f-droid. I love it. 
Best regards. 
Tobias
