### ISSUE TITLE
App does not ask for storage permissions on OPML import/export on API 23+

### ISSUE THREAD

**Issue by vanitasvitae** [Etuldan/spaRSS#176]
Hi!
When installed on a device with API lvl. 23+, spaRSS does not request permission to read/write external storage on its own. Importing/exporting OPML files fails without informing the user why.
The user has to grant the permission "by hand" to make this work.

**Comment by Etuldan** [comment]
Accepted and reproduce on my Nexus4 Android6

**Comment by Etuldan** [comment]
Thanks for the pull request :)
Integrated (w/o the non-english strings, as it's better to let them null instead of in english)
I'll build a new release today, push it to GooglePlay, and the FDroid team will be able to build it soon.

**Comment by vanitasvitae** [comment]
> Integrated (w/o the non-english strings, as it's better to let them null instead of in english)
That's why I seperated the changes in two commits :+1:
