### ISSUE TITLE
Additional RSS fields? 

### ISSUE THREAD

**Issue by LukeOwncloud** [Etuldan/spaRSS#186]
I am missing some optional RSS fields. Most notably: 

- author
- category
- (channel) 

Would it make sense to add an option which allows the user to choose whether these fields should be shown if available? I'd like them to be added to the overview list? 

Any thoughts anybody?

**Comment by jonesman** [comment]
I have been missing a category setting in the feed options too, i'm not sure how to move feeds between categories

**Comment by LukeOwncloud** [comment]
@jonesman I don't quite understand what you mean. I am talking about data that is provided by the feed itself (c.f. elements `author` and `category` in http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt). As the author seems most valuable to me, I just created a pull request (https://github.com/Etuldan/spaRSS/pull/192) which displays the author in the feed list (only if available).

**Comment by jonesman** [comment]
Oh OK, got it, great that you went out to fix that. What i meant were the categories/groups created in the reader. I will also try adding a dropdown to the feed properties for that.
