### ISSUE TITLE
full content not working with arstechnica feed

### ISSUE THREAD

**Issue by Spleeeno** [Etuldan/spaRSS#205]
hey, so I tried the main feed (http://feeds.arstechnica.com/arstechnica/index) with full content ticked on flym 1.6.5 ( pre material design - working), flym 1.9.1 (working) and sparss 1.11.5 (not working).
so it worked wit pre-fork flym, after-fork flym, but not in sparss - any reason for that?
seems like a really weird regression...

**Comment by Etuldan** [comment]
I try with the 1.11.5 on my device, and I'm able to get the fullcontent article out of box (from the feed you provided).
Does it occurs for every article in the feed, or only for some ones ? 
I know, it could be annoying, but did you try to 'reset' spaRSS (clear cache & data or uninstall/reinstall)

Also, did the build is from GooglePlay, or from FDroid ?

**Comment by Spleeeno** [comment]
I'm using the FDroid build.
And I've just tried reinstalling and clearing cache (and even deleting the backup opml): still the same behaviour.
Even when I just do a fresh install, only add the one feed, change no default options (full content is ticked by default) - it still tells gives me the link to "read the ... remaining paragraphs" at the end of each article

**Comment by KAMiKAZOW** [comment]
Same here. With Golem.de, Softpedia etc.

Maybe it's a regression with Android 4.4?

**Comment by Etuldan** [comment]
Ok my bad, reproduced.
I'll try to debug it this evening/tomorrow

It may be related to the new version, did you try/had the same issue with the release 1.11.4 ?

**Comment by Spleeeno** [comment]
works fine on 1.11.4

on a side note: I actually prefer the round preview pic behaviour in 1.11.5 - it doesnt load the previews for any feeds.
always hated the fact that even with pictures disabled, you just couldnt get rid of those preview pics (see https://github.com/Etuldan/spaRSS/issues/108, https://github.com/Etuldan/spaRSS/issues/198 and https://github.com/Etuldan/spaRSS/issues/2 )
