### ISSUE TITLE
Wrong link used when "show full content" or "open in browser"

### ISSUE THREAD

**Issue by 1-eric** [Etuldan/spaRSS#206]
I have a problem with messages from this feed: [http://www.nu.nl/rss/algemeen](http://www.nu.nl/rss/algemeen).

The summary of the message is correct, but the wrong link is used when I want to see the full content in spaRSS or in a browser.

I've looked in to the source of the feed with a text editor.
The correct link is the link between `<link>...</link>`, for example: 
`<link>
http://www.nu.nl/algemeen/4270751/vs-wijst-burgers-risico-aanslagen-tijdens-ek-in-frankrijk.html
</link>`

But spaRSS is using the link between `<atom:link href=.../>`, for example: 
`<atom:link href="http://nu.nl/voetbal/4270577/overzicht-spelers-ek-missen-blessure.html" type="text/html" rel="related" title="Overzicht: Spelers die het EK missen door een blessure"/>`

Flym and Sparse rss also have this problem.

**Comment by Etuldan** [comment]
I'm not sure about, it, a I need more research, but I think that the atom:link link should be the URL of the news. If this is true, it means that the issue is on the nu.nl website side.

See more here : http://www.rssboard.org/rss-profile#namespace-elements-atom-link

On other completely different RSS reader (which are not forks from Sparse rss, Flym, or spaRSS, does the "open in browser" feature work for this website ?

**Comment by 1-eric** [comment]
The atom:link element has `rel="related"`, so probably nu.nl wants to notify the readers of related news items.
I'll translate the 2 links from my first posting.

The link between `<link>...</link>`:
The US warns us for the risk of terrorist attacks during the football European Championship in France.

The atom:link link:
A list of players that will miss the football European Championship because of injury.

Akregator, which is an RSS reader on a Linux/KDE computer, will open the first link.

**Comment by Etuldan** [comment]
Oh, you seems right, as I didn't pay attention to the `rel="related"` .
My first (and seems wrong) understanding was for a `rel="self"`

So it seems to be indeed a bug in spaRSS (and Flym and sparse rss).
I'll try to fix it.

Thank you for the report and your investigation :)
