### ISSUE TITLE
spaRSS version 1.11.7 (F-Droid build) linking issue with heise online news feed

### ISSUE THREAD

**Issue by x2k13** [Etuldan/spaRSS#209]
When opening an entry in heise online news feed, tapping the title doesn't send you to the related page.
Instead you'll end up with an empty window in spaRSS. Selecting the overflow menu item "open in browser" pops you back to the feed's entry list. See attached .gif! Thanks for the great App!

![sparss_issue](https://cloud.githubusercontent.com/assets/13673423/15972014/5ffff0a2-2f3c-11e6-9594-4fa8fa07167f.gif)

**Comment by x2k13** [comment]
#208

**Comment by SecTec** [comment]
Yes it is ^^
