### ISSUE TITLE
Button marked all as read

### ISSUE THREAD

**Issue by Zitronella** [Etuldan/spaRSS#210]
Hi i changed from Flym to spaRSS, and it is good, but i miss one for my ‎necessary thing: The button "marked all as read". Could you please build it in? Thanks

**Comment by x2k13** [comment]
@Zitronella it's already there.
Open burger menu, tap on settings (the little cogwheel), scroll down and tick the checkbox next to the entry for the mark all as read button setting, done!

**Comment by Zitronella** [comment]
Oh my god, sorry i did not see this. Thank you very much, all is fine ;)
