### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by stoertie** [Etuldan/spaRSS#226]
Hi @all,

I have installed spaRSS at my Zenpad 8.0 and installed the feed-adress (http://forum.xxxxx.de/feed.php) of my PHPBB forum (Vers. 3.1.10). I also stored my login data (username and password) at "HTTP-Authentisierung", but when I update the feed, I just get new posts from open area of the forum. New post from the forums that need a login are not shown.

When I change the Link to "HTTPS://..." I get the message:
Fehler:java.security.cert.CertPathValidatorException: Trust anchor for certification Path not found.

What can I do, to get also the new posts from the area, that needs a login?

Best regards
Michael

**Comment by Etuldan** [comment]
"HTTP-Authentisierung" will probably not work in your case, at it's related to https://en.wikipedia.org/wiki/Basic_access_authentication
You may try to use the cookie auth feature:
Login to your forum with a browser, find the auth cookie, then copy it (text) and paste it in the spaRSS feed option (cookie setting)

**Comment by stoertie** [comment]
Thanks a lot! That brought me to an other way ghat work... I just addet "?auth=http" to the link of the forum. That works perfect. - Thanks a lot!

**Comment by stoertie** [comment]
*oups* Sorry, I have an additional question... maybe my last post comes too early. :-(

Now, after adding "?auth=http", spaRSS shows the new posts in the protected area, but wen I click to the headline there comes the forums request to register in the forum. 
When I open the options in right upper corner and click to "show complete content", the check mark disappears and the whole content of the post is shown. - That's a little bit uncomfortable., isn't it? Is that normal?

Could you tell me where I can find the auth cookie in firefox? I just found the normal cookies... after login there are three cookies in the list. these cookies named: phpbb3_rrsr4_sid, phpbb3_rrsr4_k and phpbb3_rrsr4_u . Which one is the auth cookie? 

Thanks a lot in advance for your patience

regards
Michael

**Comment by Etuldan** [comment]
Well, about the full content : 
spaRSS can grab the 'full content' of an news. For example, some web newspapers only set in their RSS feed a few lines, and the user have to click on the link 'read more', which will redirect to the full website.
spaRSS is able the parse the 'full website', and extract the news content (without any header, footer, ...)

But, in your case, the PhpBB engine seems to include the full content in the RSS feed (the .xml file). But as the option 'show complete content' is checked, spaRSS try to parse the full PhpBB topic, which is of course, in your case, as it's password protected, fails. Disabling the "show complete content' will work, and you can set this option for all the future news of your PhpBB RSS feed, in the feed option.

About cookies, it depends on the website, and I don't know exctly what is the correct one for PhpBB, but, as I said before, you don't have to use it, in this case :)

**Comment by stoertie** [comment]
Hi,

thanks again.

The check mark was the soloution. It confuses me a little, that - in my case - I have to uncheck it for showing the complete content. *oups*
So, for all PHPBB3 users:

1. Input the forum link: http://domain.tld/feed.php?auth=http
2. Input username and password
3. Uncheck "download whole content" (vollen Text abrufen)

Regards
Michael
