### ISSUE TITLE
a feed doesn't work well

### ISSUE THREAD

**Issue by ildar** [Etuldan/spaRSS#23]
http://vk2rss.sarbas.org/rss/id-11004967
tested with the latest alpha release

**Comment by Etuldan** [comment]
Does this feed work with the stable release ? (from GPlay/FDroid)

**Comment by ildar** [comment]
Flym version 1.8.1 doesn't work either.
Should I annoy Flym author as well?

-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by Etuldan** [comment]
Flym author has no more time to improve/fix bug, that's why I forked it. I doubt if he will be able (about time) to fix this on his version.

Thank you for the information

**Comment by Etuldan** [comment]
Seems to be related to the <![CDATA[ encapsulation.
I'll try to debug it later.

**Comment by ildar** [comment]
Excuse me, can I raise this one up? This bug is very annoying preventing
the whole class of feeds to be read.

**Comment by Etuldan** [comment]
Sorry for the late response.
I analyzed the code and the RSS file, and there is no <title> element in each <item>.
I'll choose the <url> element if there is no <title>.

**Comment by ildar** [comment]
Emm, is that against standards? then I can report to the feed provider.

**Comment by Etuldan** [comment]
According to this http://www.rssboard.org/rss-specification , a feed entry should contain at least "title", "link" and "description".
However, I don't think this document is the official one.

**Comment by ildar** [comment]
Anyway I reported:
https://github.com/tsarbas/tsarbas.github.io/issues/1#issuecomment-141212741

**Comment by ildar** [comment]
The provider fixed the feed and it works now.
Thanks for finding the root cause.
