### ISSUE TITLE
Preload the feeds in the app

### ISSUE THREAD

**Issue by suds7** [Etuldan/spaRSS#251]
How to preload the feeds in the app

**Comment by Etuldan** [comment]
What do you mean by preload ?
spaRSS should preload every feed entry if you have an internet connection, check in the spaRSS options.

**Comment by suds7** [comment]
For example when someone install the apk i want them to see the feed of my site by default. I'm not sure where i need to add the feed so that when app will start. It will load the feed of my site.

**Comment by suds7** [comment]
This is related to issue#203. Closing this issue.
