### ISSUE TITLE
spaRSS doesn't show diaspora feed content by default

### ISSUE THREAD

**Issue by bezcitu** [Etuldan/spaRSS#252]
When I add a diaspora Atom feed like https://diaspora.zone/public/holger.atom or https://joindiaspora.com/public/linux.atom to spaRSS, it only shows "Powered by diaspora*" as full content. After deactivating "Show full content", the full content is actually shown. So it's reversed.

**Comment by Cj-Malone** [comment]
"Show full content" actually means scrape the URL. I think that _feature_ should be disabled on Atom entries with a content element (not just a summary tag) and RSS items with content:encoded (content being http://purl.org/rss/1.0/modules/content/)

**Comment by Etuldan** [comment]
As @Cj-Malone stated, "Show full content" is a URL scrapped and content extractor. It might fail, depending on the webpage (not the .rss or .atom on, but the Html page)
If it works for diaspora, as they include the full content in their feed, so simply use the regular rss feature ;)
