### ISSUE TITLE
Export Favorites

### ISSUE THREAD

**Issue by trmendes** [Etuldan/spaRSS#258]
It would be nice if the export feature saves the favorites too. Or a backup feature where I could save all the feeds, plus the entries I've marked as favorites.

**Comment by Alcofribas** [comment]
@trmendes, this seems to be a near duplicate of #175. Maybe you want to add your ideas there instead of opening a new issue? Best, Alco

**Comment by trmendes** [comment]
@alcofibras. sorry about that. I was checking before opening it but it seens like I made it wrong. Gonna write it there.
