### ISSUE TITLE
[Feature Request] Sync with OPML file (local/http)

### ISSUE THREAD

**Issue by nereusx** [Etuldan/spaRSS#28]
I have the problem that my older family members discovered the enjoy of reading news from internet. So, I need something to update their sources automagically.

For now I use owncloud [in my PC with ddns], and its news client. Also, I made today a page with news in JQuery in my personal site to replace it, but I would prefer just to update an opml file. In my case, no they cannot go to xxx, download the file and then import it...

btw, I shaw the spaRSS a few days ago and I loved, gReader removed at last :+1:

**Comment by Etuldan** [comment]
So, you want a download/sync option for the OPML importation ?
I'm not sure a the moment to do that, as it's not the main role of the app.

But, maybe you can sync the OPML file with owncloud (owncloud only, not using owncloud news client)
So they have to import (manually) the file (which will be previously automatically updated)
If it's fit with your idea, I'll maybe add a feature to import periodically the specified OPML file in spaRSS.

**Comment by nereusx** [comment]
> So, you want a download/sync option for the OPML importation ?

Yes --> if file has been updated; remove the entries of previous file and add the entries of the new.

This is what I need, I ll be happy with this :-D

Anyway I find more interresting to have the posibility to use OPML files as source, that could group RSSes without make mess the reader. For example I need a RSS collection for news from Iceland, since at media, Iceland does not exists any more (they closed the banks)... That would be usefull for a certain time but after that, it will not. Think 3-4 subjects like Iceland and you catch the idea.
