### ISSUE TITLE
Add a URLs export/import option

### ISSUE THREAD

**Issue by b16r05** [Etuldan/spaRSS#281]
For whatever reason [ updating android, flashing custom ROM, resetting app, etc. ], the spaRSS needs to be reinstalled and all the URLs added. An option to export URLs to file, and then, import once the OS is up and running, would be helpful.

**Comment by b16r05** [comment]
My mistake, this is already present. 
In Flym, on the Feeds page, I exported URLs to an OPML file. In spaRSS, I imported URLs from the OPML file. 
Please close this issue.

**Comment by jonesman** [comment]
You should be able to close it if you opened it
