### ISSUE TITLE
[FR] per-feed expire time

### ISSUE THREAD

**Issue by ildar** [Etuldan/spaRSS#3]
It was: https://github.com/FredJul/Flym/issues/125
I still desperately need it:
Have per-feed setting on how long to keep entries. That's because some feeds get overflowed very quickly and some are not while having a long history. So one expire time for all feeds is inappropriate.
I now have "Do not delete" and Flym got very slow at 70M+ data size.

**Comment by Etuldan** [comment]
As the link is broken, here is the content (google cache source):



I have almost 10000 items. That's slow :angry:
Looking at my feeds I see that along with usual news feeds injecting lots of items I also have some oldish small feeds to read later.
So for me there's no good choice for "Time interval to keep entries".
To fix this there may be a per-feed setting or
another way to limit entries pollution: by number of entries
What do you think?


​Also, I started to dig the FeedEx.db and found that `date` (and prbably
`fetch_date`) are non-standard format in terms of SQLite:
sqlite> select date from entries where feedid=7;
1369383485000
1369894874000
sqlite> select date(date) from entries where feedid=7;
1698789-19650109-20
1698789-19650109-20
sqlite> select date('now') from entries where feedid=7;
2014-06-03
2014-06-03

I wanted to clean my DB manually but seem to stuck. :(





Hi, the value in the DB is just a unix timestamp with milliseconds (a standard date/time format in many languages, including java!)

in a unix/linux box you can convert it removing the trailing 000 and using the date command as this:
$ date -d '@1369383485'
ven 24 mag 2013, 10.18.05, CEST




So the workaround for this issue:
0. Get into the DB:
`sqlite3 /data/data/net.fred.feedex/databases/FeedEx.db`
1. Get entries number per feed:
`select feedid,count (*) from entries group by feedid order by count (*);`
2. Delete entries older then 2 month that aren't in favorites for
feedid=FEEDID(substitute):
`delete from entries where favorite is null and
datetime(date/1000,'unixepoch') < datetime('now','-2 month') and
feedid=FEEDID;`

**Comment by ildar** [comment]
great :) thanx
>
>

**Comment by Etuldan** [comment]
So, to be clear, you want the option "Time that entries will be kept" configurable per feed and not for all the application ?
Nice idea !

I'll maybe let this option (for all feed) for default settings, and add the new option (per feed) that will overload the default setting if set.

**Comment by ildar** [comment]
exactly. That would be great.

**Comment by Etuldan** [comment]
Feature added in experimental branch.
If you can't build the APK, I can do it and send it to you for testing purpose (you will have to uninstall the F-Droid/Gplay one before installing the experimental one)

**Comment by ildar** [comment]
That's so great! Thanks!
Yes, I can do pre-release testing if required. Then please share an apk for
me.
Otherwise when a version with this commit will be released?

**Comment by Etuldan** [comment]
If I manage to fix some other bugs, I hope the 'stable' version will be release in two days max.
Here is the pre-release : https://github.com/Etuldan/spaRSS/releases/tag/v1.10-alpha

**Comment by ildar** [comment]
Hi! Thanks for working on the issue, but I think the feature doesn't work
right.
What I do:
1. Stop spaRSS in Android
2. copy database from the Flym (i.e. FeedEx.db files)
3. Start spaRSS
4. Change items deletion period in Settings to Never
5. Change a feed's period to 1 month
6. Update the feed

Unfortunately I see new items appearing but items older then 1 month
weren't deleted.
I am not sure when the deletion process should start but I don't see any
signs it worked.

**Comment by Etuldan** [comment]
Thank you for trying !
Could you try with a clean database, with some feed set to 1 day ? (so you'll have to wait at least 1 day to check if it works)
I'll also try to debug it, but, as in my rapid tests (with always a clean database), the feature seems to work.

**Comment by ildar** [comment]
Ok. When the cleanup phase is done?
>
>

**Comment by Etuldan** [comment]
It should be done when the current existing one (in a stable APK) is done.

**Comment by ildar** [comment]
No, sorry.
I mean when the cleanup function is called? Before update, after update,
postponed ?

**Comment by Etuldan** [comment]
Hum, what I want to say : 
The new cleanup function (per feed) is call at the same time (just after to be precise) the actual cleanup function (for all feeds).
I'm still not quite 'fluent' with the whole project source, so I don't know yet when exactly the both functions are called.

**Comment by ildar** [comment]
Is this all in the apk that was published a few days ago?

**Comment by Etuldan** [comment]
Yes, it should be in the 1.10-alpha APK.

**Comment by Etuldan** [comment]
Indeed, It still doesn't work.

**Comment by Etuldan** [comment]
Should be OK now.
Commit in experimental branch
Binary here https://github.com/Etuldan/spaRSS/releases/tag/v1.10-alpha3

**Comment by ildar** [comment]
great work! seems to work now!
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/
