### ISSUE TITLE
Cache off the app growing

### ISSUE THREAD

**Issue by Etuldan** [Etuldan/spaRSS#37]
In daily use the cache of the app grows more and more.
It blocks a great amount of memory on my device. Would it be possible to include an option "delete cache-files older then x days"? 
Or maybe link the cache to the existing option for deleting old feeds?

**Comment by ildar** [comment]
I was sure that the cached pages are dropped together with the
corresponding items. Is that wrong?
Well, I was bothered with active feeds polluting the app's database until
per-feed expiration was implemented.
If you're annoyed by cache, not the database then you might want just to
clean cache time to time with the usual android tool (from application info)

чт, 16 июля 2015, 15:17, RENAUD-GOUD Arnaud <notifications@github.com>:

> In daily use the cache of the app grows more and more.
> It blocks a great amount of memory on my device. Would it be possible to
> include an option "delete cache-files older then x days"?
> Or maybe link the cache to the existing option for deleting old feeds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Etuldan/spaRSS/issues/37>.
>
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by Etuldan** [comment]
The issue I reported was sent by a user of spaRSS in my email inbox. (and he prefer to stay 'private')
I'll look into this issue soon.
He also knows the "clean cache" feature from the Android OS, but, this is not the best way to do it ;)

**Comment by klawdhfzasjhaa** [comment]
Mine is now 1.7 GB.. :/
As suggested before, when feed expiration date is expired, corresponding cache files should be deleted too.
Thanks for your efforts, Etuldan. :)

**Comment by Etuldan** [comment]
@klawdhfzasjhaa : could you check that the "Time that the entries will be kept" global setting in not set to "Always" ?

**Comment by klawdhfzasjhaa** [comment]
@Etuldan : It's set to 2 days.

**Comment by mmirg** [comment]
My apologies if this is a necrobump, but I seem to still have this issue and regularly manually clear my cache.  The bug appears to have been fixed in the most recent Flym release in commit f29ffc8 [https://github.com/FredJul/Flym/commit/f29ffc8e34e4fdff45fdaa31fd027f00dbe16805](url) and I've verified this through use.  It didn't seem like SpaRSS had been rebased on that code yet, but I'm sorry if I'm mistaken.

**Comment by Etuldan** [comment]
Thanks a lot @mmirg and don't worry about "necrobump" ;)
This will definitely help a lot, I hope !

**Comment by FloGatt** [comment]
Same here. Cache is growing and growing and app starts lagging...

@Etuldan 
> I'll look into this issue soon.

**Comment by Ano24** [comment]
The App is realy greate, but this BUG is super annoying. I always have to clean the Cache or the App is going to stop working -_-
