### ISSUE TITLE
App crashes when marked as 'Protected App' in Cyanogenmod 12.

### ISSUE THREAD

**Issue by anoadragon453** [Etuldan/spaRSS#40]
Hey there. Seems to be an issue with both Flym and SpaRSS. When set as a protected app in Cyanogenmod, either tapping on an article, trying to view the about page or tapping on a feed from the 'pencil' view in the sidebar, the app crashes with the message "unfortunately SpaRSS has stopped working". Not really sure what the app is trying to access and thus protected mode is preventing it from using, though it seems to happen in only those three cases, regardless of the feed URL.

Cyanogenmod Nightly Build 2015-01-29. LG G3 d851. Android 5.0.2.

**Comment by Etuldan** [comment]
I have also a CyanogenMod release (on a Nexus4), with the "Protected App" feature enabled (even for spaRSS :p ), and I'm not able to reproduce your issue. (but, yes, I'm on Android 4.4.4, I have to device with Android 5.x)

Concerning the "About" page, maybe you don't have the latest release ? https://github.com/Etuldan/spaRSS/releases/tag/v1.10.0 / https://github.com/Etuldan/spaRSS/issues/6

Do you use the GooglePlay app, the F-Droid one or your spaRSS own build ?

**Comment by anoadragon453** [comment]
I've got the latest version from F-Droid installed, v1.10.0. Bug still reproducible on the device. Still running the same nightly build. 

I've noticed sometimes apps crash when the 'Privacy Guard'feature is enabled for that app  (e.g. Netflix), yet disabling the feature for SpaRSS made no difference in this case.

**Comment by ildar** [comment]
Might be a CM bug. Could you/ would you upgrade to a more recent nightly?
Also to be more specific would you please send the adb logcat?

**Comment by Etuldan** [comment]
@anoadragon453 any news about ?
Do you reproduce the issue ?

**Comment by anoadragon453** [comment]
Ah yes. I'm not running the latest Cyanogenmod but have been meaning to at some point. Unfortunately my failed attempts in the past seem to hint that it will require a full reset, of which I've put off for the last few months.

In short I'm not able to test on the latest Cyanogenmod, however on the current cm even with the latest upgrade it still crashes when marked a protected app. I've learned to live with it, but when I finally get around to upgrading, or someone else with the latest version can chime in, I'll let you know the result.

**Comment by Etuldan** [comment]
WontFix label until someone got the same issue (or you can reproduce with a newer version of CM)

**Comment by ildar** [comment]
Ok, I just tested it on CM 12.1. I don't confirm crashes in all the cases
you wrote.

**Comment by anoadragon453** [comment]
Good to hear perhaps it's just an isolated issue then.

**Comment by anoadragon453** [comment]
Can confirm working on latest CyanogenMod nightly.
