### ISSUE TITLE
Refresh button is using wrong Material icon

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#47]
@Etuldan :

For the refresh button, spaRSS currently seems to be using the "autorenew" Material icon which has two arrows.

Could you please change it to the "refresh" Material icon which has one arrow:

https://www.google.com/design/icons/
https://google.github.io/material-design-icons/

?

It would be much appreciated.

Regards

**Comment by Etuldan** [comment]
OK for the icon (but what a shame, the webpage made by google isn't Ctrl+F [item] friendly ...
So, I have to use this one, correct ? : https://www.google.com/design/icons/#ic_refresh

**Comment by wp9015362** [comment]
Yes, that is the one that I was referring to.

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> but what a shame, the webpage made by google isn't Ctrl+F [item] friendly ...

The page (https://www.google.com/design/icons/) has a built-in search at the very top of the page.

Just saying :wink:.

**Comment by Etuldan** [comment]
Fixed in the Experimental branch
