### ISSUE TITLE
Pressing back button does not close the left panel

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#49]
@Etuldan :

When the left panel is open and you press the back button, the left panel stays open and [a message comes up which says "Press back once more to exit"](https://github.com/Etuldan/spaRSS/issues/50).

IMHO this feels really strange.

Could you please change it so that when the left panel is open and the back button is being pressed, the left panel simply closes?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
PS:

Since @ildar is always referring to and comparing with the official Google Material Design apps:

All official Google Material Design apps that I know of that have a left panel (such as Google Play Store, Gmail etc.), all close the left panel when the back button is being pressed, so spaRSS should do the same :stuck_out_tongue: .

**Comment by ildar** [comment]
Sorry if I bothered you with it :)))

**Comment by Etuldan** [comment]
Fixed in the Experimental branch
