### ISSUE TITLE
turkish char issues

### ISSUE THREAD

**Issue by irregularisnotrandom** [Etuldan/spaRSS#5]
Try this please 
http://www.acikradyo.com.tr/i/rss/Acik_Gazete.xml

**Comment by Etuldan** [comment]
I can't see article link with text in the RSS you provide (only music MP3 attached files).

In http://www.turkiyegazetesi.com.tr/rss/rss.xml (another turkish encoded website), all seems good with spaRSS. If you have another RSS feed with text content inside with a reproductable issue ?

**Comment by Etuldan** [comment]
OK, the issue is about the charset detection.
Thank you for reporting !

**Comment by Etuldan** [comment]
Indeed, the website that you provide declare a different charset that the one it use.
The declaration is "iso-8859-9", while the real encoding seems to be UTF-8.
There is nothing I can do without breaking all other encoding.
