### ISSUE TITLE
Please remove "Show original text" button

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#52]
@Etuldan :

When you press the "Retrieve the full text" button and the text has been retrieved, the button changes to "Show original text", which retracts the text again when being pressed.

Why? What for?

Why would anyone want to do that?

And why is it called "Show original text"? The retracted text clearly is not the original text.

IMHO this button should simply be removed.

Once the "Retrieve the full text" button has been pressed and the text has been retrieved, the button should simply disappear IMHO.

Any chance you could do that?

Regards

**Comment by ildar** [comment]
Agree to change the ui/ux but disagree to just remove it.
Maybe it's worth to mutate it to the floating button in the right bottom.

**Comment by Etuldan** [comment]
@ildar : not a bad idea to change the floating button to this feature.
@wp9015362 : agree that the text should be modified. But I also think like ildar that we have to let the user switch back to the classic mode (for example when the full text is buggy)
