### ISSUE TITLE
Please allow to increase the text size even further

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#53]
@Etuldan :

The "Text size" option is really nice.

But would there be any chance you could allow to increase the size of the text even further than "+3" (i.e. adding +4, +5, etc.)?

It would be much appreciated.

Regards

**Comment by Etuldan** [comment]
Fixed in the Experimental branch 
Size +4 and +5 added.

**Comment by wp9015362** [comment]
@Etuldan :

This is a very welcomed change. Thanks a lot!

But I noticed that you actually only added +4 and +5 :laughing: .

When I said "i.e. adding +4, +5, etc.", I thought it was obvious that it should go even beyond +5 :wink:.

It would be nice if you could allow to increase the text size even further and be a bit more generous about it.

How about allowing to increase it up to +10 for example?

At the end of the day, spaRSS is a news reader and it's being used to read text, so the text size option may be quite important for some.

The text size option should have a generous range of configurability IMHO.

It would be nice if you could make the range a bit more generous.

Regards
