### ISSUE TITLE
Please remove "jump to" feature from scrollbar in feed entry list

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#55]
@Etuldan :

In the spaRSS feed entry list, you can actually press and hold the scrollbar and drag it up and down.

I have never really seen that in another Android app. But that is not really the issue.

The issue is:

When the scollbar is being shown, you can tap on any position of the scrollbar and then the scrollbar immediately "jumps" to this position.

This can be really annoying.

Because:

On several occasions I was reading through the feed entry list and accidently touched the scrollbar and it suddenly jumped to an entirely different position.

No other Android app I know of is doing that.

Could you please remove this "jump to" feature from the scrollbar in the feed entry list?

It would be much appreciated.

Regards

**Comment by ildar** [comment]
This is the standard Android text/list widget with the thick scrollbar,
seen in other apps quite often.
The dragable and tapable scrolling is the must there. No offence.

**Comment by wp9015362** [comment]
> @ildar wrote:
> 
> This is the standard Android text/list widget with the thick scrollbar, seen in other apps quite often.

Please name at least one other app.

> @ildar wrote:
> 
> The dragable and tapable scrolling is the must there.

Dragable: Probably.
Tabpable: No!

Regards

**Comment by Etuldan** [comment]
@wp9015362 
F-Droid app (v0.95.1) is working like described. 
Contact (AOSP app in CM11)

(so spaRSS is not the only one)

Anyway, for a RSS reader it's mabye not the better choice.
But as the list can be huge, the user should be able to jump easily and quickly (without drag, wait for 5 sec for autoscroll, press again to stop the autoscroll)

**Comment by wp9015362** [comment]
@Etuldan :

As far as I can tell, the contact app only works like that because you can jump to some specific points, namely the letters in the alphabet (e.g. A, B, C, etc.).

The spaRSS feeds entry list however does not have such specific points.

In the contact app you jump to specific points (alphabet letters).

Makes (somewhat) sense.

In spaRSS you are jumping to random points.

Makes no sense at all IMHO!

Regards

**Comment by wp9015362** [comment]
@Etuldan :

I've got an idea over there:

https://github.com/Etuldan/spaRSS/issues/64

Maybe if you would [separate the feed entries in the feed entry list by inserting the date between the feed entries for each day](https://github.com/Etuldan/spaRSS/issues/64), the jump to scrollbar feature could finally be put to good use to allow to jump to specific dates instead of random points :wink:?

Regards

**Comment by Etuldan** [comment]
Idea is not bad.
I'll fix this issue (by removing the "jump" feature in the scroll list). I'll re-add it with Date-Order later ;)

**Comment by wp9015362** [comment]
@Etuldan :

Now that you have disabled the jump feature from the scrollbar in the feed entries list, the scrollbar also no longer is draggable.

Would it be possible to disable the jump feature from the scrollbar, but still leave the drag feature enabled?

Regards
