### ISSUE TITLE
"Time that the entries will be kept" global option does not synchronize with the per feed option

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#57]
@Etuldan :

In the global settings there is an option called "Time that the entries will be kept".

The same option is also available as a per feed option in the edit feed settings.

When I set the global option to "2 days" for example, then the per feed option still stays at "Forever".

Could you please fix that?

Or alternatively:

Could you please remove the per feed option? To me the per feed option doesn't make much sense.

Regards

**Comment by ildar** [comment]
It makes a huge sense, read the corresponding Issue for details.

**Comment by Etuldan** [comment]
There is a 'type' error, the "Forever" in the Feed option should be "Default option".

**Comment by wp9015362** [comment]
Should get the "bug" label then :wink:.

**Comment by Etuldan** [comment]
Typo fixed in the Experimental branch (still missing translations for all languages except EN and FR)
