### ISSUE TITLE
When opening "Edit feed" page, keyboard is immediately being displayed and hides some options

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#58]
@Etuldan :

When opening the "Edit feed" page, the cursor immediately and automatically jumps to the "URL address" field and opens the keyboard, which is then hiding some options.

Could you please fix that by making the cursor not jump automatically to the "URL address" field when opening the "Edit feed" page?

As already explained [in the other issue](https://github.com/Etuldan/spaRSS/issues/45), this actually prevented me from seeing the "Retreive the full text" and "Time that the entries will be kept" per feed options.

Regards

**Comment by Etuldan** [comment]
Fixed in the Experimental branch :
Auto-select is removed.
New Advanced Tab added.
