### ISSUE TITLE
The button/icon, which opens the left panel, makes an awkward rotational movement while the left panel is being opened

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#61]
@Etuldan :

I noticed that the the button/icon, which opens the left panel, makes an awkward rotational movement while the left panel is being opened.

Could you please fix that?

Regards

**Comment by Etuldan** [comment]
Indeed, it's useless on (my) Nexus4, but as this function was implemented, maybe it can be useful in some cases ?

**Comment by wp9015362** [comment]
@Etuldan :

I had a look a the Google Material Design guidelines to see if I can find any information regarding this rotational animation.

And I indeed was able to find it.

It is shown over there (see "Radial action" animaton):

 https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input

And it is also shown over there (see the two animations at the top of the page):

https://www.google.com/design/spec/animation/delightful-details.html

But, as you can see, it is used to make the ["menu" icon](https://www.google.com/design/icons/#ic_menu) transition into the ["arrow back" icon](https://www.google.com/design/icons/#ic_arrow_back).

However, in spaRSS the menu icon does not transition into the arrow back icon. Or at least not visibly, since the left panel hovers over the menu button, essentially making the area where the menu button is invisible.

I also had a look at the latest version of the official Gmail app.

The latest version of the official Gmail app does __not__ rotate the menu button when the left panel is being opened.

So, IMHO spaRSS also should not rotate the menu button when the left panel is being opened.

Regards
