### ISSUE TITLE
Some icons are being grayed out even though they should not be grayed out

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#62]
@Etuldan :

I noticed that some of the icons in spaRSS look like as if they would be grayed out.

Just some examples:

The refresh icon and the mark all as read icon as well as the hide/show read entries icon for example all are gray instead of white.

Could you please make the gray icons change to white?

No need for them to be gray IMHO.

It would be much appreciated.

Regards

**Comment by Etuldan** [comment]
Yes, I'm currently reviewing all color/icons.
Icons should be black or white (depends on dark/light theme)
