### ISSUE TITLE
spaRSS does not use Material icons everywhere

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#63]
@Etuldan :

Additionally to what I already mentioned in https://github.com/Etuldan/spaRSS/issues/47, I noticed that spaRSS does not seem to be using Material icons everywhere.

Maybe the icons that are currently being used in spaRSS are from an older Android icon version, not sure.

But most of them definitely are not the new Material icons.

Could you please make spaRSS use Material icons everywhere:

https://www.google.com/design/icons/
https://google.github.io/material-design-icons/

?

I've already searched all the proper Material icons for you :stuck_out_tongue: , namely:

The edit icon should be replaced with the proper "edit" Material icon, see:
https://www.google.com/design/icons/#ic_edit

The search icon should be replaced with the proper "search" Material icon, see:
https://www.google.com/design/icons/#ic_search

The settings icon should be replaced with the proper "settings" Material icon, see:
https://www.google.com/design/icons/#ic_settings

The "Add group" icon on the edit feed page should be replaced with the "playlist add" Material icon, see:
https://www.google.com/design/icons/#ic_playlist_add
(The ["group add" Material icon](https://www.google.com/design/icons/#ic_group_add) would not be appropriate in this case IMHO.)

The reorder icon should be replaced with the proper "reorder" Material icon, see:
https://www.google.com/design/icons/#ic_reorder

The star and star boder icons should be replaced with the proper "star" and "star border" Material icons, see:
https://www.google.com/design/icons/#ic_star
https://www.google.com/design/icons/#ic_star_border

The fullscreen icon should be replaced with the proper "fullscreen" Material icon, see:
https://www.google.com/design/icons/#ic_fullscreen

The "Hide/Show read entries" icon should be replaced with the "remove red eye" Material icon, see:
https://www.google.com/design/icons/#ic_remove_red_eye

The refresh icon should be replaced with the proper "refresh" Material icon (as already mentioned in https://github.com/Etuldan/spaRSS/issues/47), see:
https://www.google.com/design/icons/#ic_refresh

I hope I haven't forgot any :wink:.

So, could you please replace the icons with the proper Material icons :wink:?

It would be much appreciated.

Regards

**Comment by Etuldan** [comment]
Yes, I'm currently reviewing all color/icons.
Thanks for the list and details, greatly appreciated :)

I'll also add different resolution of icon (currently, there is only the xhdpi one)

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> Yes, I'm currently reviewing all color/icons.

Thank you very much. Looking forward to it.

The Google Material Design guidelines might be helpful for you, see:

https://www.google.com/design/spec/material-design/introduction.html

You can navigate through them via the menu button in the top left corner of the page and/or via the arrow buttons in the bottom right corner of the page.

Among many other things, the guidelines also have a section for color.

Regards
