### ISSUE TITLE
Please don't let commits rot in experimental branch

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#65]
@Etuldan :

I noticed that your commits go into an experimental branch first.

I noticed that some of the latest commits are in there for two months already.

That's quite unfortunate, because it means that I still haven't received those commits because I don't plan to compile spaRSS myself everytime it is being updated.

I would assume that most people won't compile the experimental branch for themselves either.

So the experimental branch probably does't yield you any "beta feedback" or something like that anyway, essentially rendering the experimental branch useless (at least as far as I can tell).

Can't you just move the commits to the master branch immediately, bump the version after a few commits and release it to the Google Play Store and F-Droid immediately without waiting such a long time?

It would be much appreciated if you could do something about this.

Regards

**Comment by Etuldan** [comment]
I prefer to modify in Experimental branch.
As in the stable branch, the app should be fully 'stable', and FDroid use this repo to autobuild the app (when version number is incremented).

I usually modify first in experimental, then release a pre-build (from this branch), providing .apk .
Then, if all sound good, I merge into stable, and publish to GPlay (and let FDroid publish by themself).
It may have some delay, sorry for that, I'll try to improve that for the future.

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> then release a pre-build (from this branch), providing .apk

Sorry, but at the moment I do not plan to manually install/sideload any .apk.

That would also require the "Unknown sources" option to be enabled.

And I know a lot of people don't and won't do that.

For most people, Google Play Store is the only source to install software from.

So, I am not really convinced that you will get a lot of feedback from users that way before merging into master/stable (but I could be wrong).

> @Etuldan wrote:
> 
> PS : and I hate when there is everyday a update of an app (GPlay or FDroid or ...), requiring the user to redownload all the apk for 'just a minor' update. (especially when I have a limited data plan and no wifi available)

That is a rather moot argument.

At the end of the day, as a user you could decide for yourself how regular you want to download updates.

Let's say you have ten new commits.

If you bump the version number with each commit and release ten separate updates, then the user himself could decide to either download all ten updates each time they are being released or he could simply wait until the tenth update has been released and then download it.

If he would wait until the tenth update would have been released, that would result in the same traffic as if you would have waited until the tenth commit before doing an update.

The user could decide for himself if he would have concerns about his data plan.

And users which are not concerned about it, could get the updates as soon as possible, if they want to.

And you would also get a faster feedback regarding possible regressions and you could react faster, since more people would get the update quicker.

But if you continue to wait several commits long before doing an update (like you are currently doing), then all users have to wait a long time for an update, even though they might not be concerned about their data plan.

> @Etuldan wrote:
> 
> It may have some delay, sorry for that, I'll try to improve that for the future.

Thank you.

Regards

**Comment by Etuldan** [comment]
Closed.
I'll commit in 'stable'.
Except for specific possible breaking ones.
