### ISSUE TITLE
Selected items in left panel have bad contrast with light theme

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#71]
@Etuldan :

Thanks for having fixed https://github.com/Etuldan/spaRSS/issues/48 in version 1.10.1. Much appreciated.

But the selected items in the left panel have a bad contrast when using the light theme.

Here is an example screenshot:

![Image](https://cloud.githubusercontent.com/assets/7558360/9568072/a1906098-4f3f-11e5-882a-7dfcde4edc0d.png)

As you can see, in this screenshot, "Starred" is selected.

But it uses black font and a black star icon. This doesn't mix too well with the dark blue background.

IMHO the font should and the icon be white for selected items.

Any chance you could fix that?

For comparison, here is a screenshot of the left panel in Amaze with the standard theme and standard colors:

![Image](https://cloud.githubusercontent.com/assets/7558360/9568086/16ae0362-4f40-11e5-9d05-42cb117fe0c1.png)

As you can see, it certainly does have a better contrast in comparison.

Regards

**Comment by wp9015362** [comment]
@Etuldan :

To fix this issue, please also see the "Select state" section over there:

https://www.google.com/design/spec/patterns/navigation-drawer.html

Regards

**Comment by Etuldan** [comment]
Will be done in the next release (the one with new logo / colors)
