### ISSUE TITLE
Option to disable feed/group from automatic update

### ISSUE THREAD

**Issue by gittus** [Etuldan/spaRSS#73]
@Etuldan: Thank you very much for forking Flym and continuing.

I have a feature request:
Would you please insert a "disable" option, which prevents a group or single feeds to be updated when doing an automatic update?

Background:
I have a large list of feeds and I don't want that all feeds are updated all the time. Some feeds I have only for history purposes and I don't want to retrieve them all the time (e.g. to reduce bandwith). With this option I could create a group e.g. "archive" and shift these feeds there.

Thank you.

**Comment by ildar** [comment]
First this issue have already been raised. Reading that previous issue may
help.
Second, you can update feeds individually and change a feed's URL to some
wrong value that would prevent it from being fetched.
Surely my comment doesn't answer your request fully.

**Comment by Etuldan** [comment]
@gittus : see #30
