### ISSUE TITLE
spaRSS does not adhere to Google Material Design Color Palette

### ISSUE THREAD

**Issue by wp9015362** [Etuldan/spaRSS#78]
@Etuldan :

The Google Material Design Guidelines come with a Google Material Design Color Palette, see:

https://www.google.com/design/spec/style/color.html#color-color-palette

spaRSS currently uses the following colors:

https://github.com/Etuldan/spaRSS/blob/master/mobile/src/main/res/values/colors.xml

    <color name="light_theme_color_primary">#247ab0</color>
    <color name="light_theme_color_primary_dark">#175073</color>
    <color name="dark_theme_color_primary">#175073</color>
    <color name="dark_theme_color_primary_dark">#ff10364e</color>
    <color name="dark_background">#FF000000</color>
    <color name="light_background">#FFFFFFFF</color>
    <color name="floating_action_button_disabled">#ff0b2535</color>
    <color name="dark_text">#FFFFFFFF</color>
    <color name="light_text">#FF000000</color>
    <color name="group_text">#BBBBBB</color>
    <color name="separator">#515151</color>

Apart from white, none of those colors adhere to the Google Material Design Color Palette.

Also, the floating action button uses the same color as the primary color.

This is not allowed according to the Google Material Design Guidelines. According to the Google Material Design Guidelines, a proper accent color needs to be set up for action buttons, [switches](https://github.com/Etuldan/spaRSS/issues/72), sliders and so on. And it may not be the same color as the primary color, see:

https://www.google.com/design/spec/style/color.html#color-ui-color-application

Could you please fix all of that and make spaRSS adhere to the Google Material Design Color Guidelines:

https://www.google.com/design/spec/style/color.html

?

Regards

**Comment by Etuldan** [comment]
For the dark theme, I'll use the black color ( #000000 ) as background for amoled screen (see #34 )
I'll not create another theme ('light black') 

Anyway, for the light theme mainly, it will be reworked (thanks for your remark), and "main" and "accent" colors will be adjusted.

**Comment by wp9015362** [comment]
> @Etuldan wrote:
> 
> For the dark theme, I'll use the black color ( #000000 ) as background for amoled screen (see #34 )
I'll not create another theme ('light black') 

That makes sense.

One thing I noticed about the dark theme though:

Those thin gray separation lines in each list, which separate the list entries, are very very dark. They almost blend with the black background, they are almost invisible.

IMHO their brightness should be increased a bit. Otherwise they are pretty useless.

> @Etuldan wrote:
> 
> Anyway, for the light theme mainly, it will be reworked (thanks for your remark), and "main" and "accent" colors will be adjusted.

Thank you very much.

May I ask what colors you are planning to use for those?

PS:

When you are at it, it would also be nice if you could use the ["ic_visibility_off" Material icon](https://www.google.com/design/icons/#ic_visibility_off) for the floating action button, instead of dimming the floating action button, as requested in:

https://github.com/Etuldan/spaRSS/issues/69

Regards

**Comment by wp9015362** [comment]
@Etuldan :

So, you switched to a new logo now: https://github.com/Etuldan/spaRSS/commit/3e90c48c424121aac5fefa0ccdc91716de5e2de7

May I ask which colors you are planning to use for the app now?

Regards

**Comment by Etuldan** [comment]
Main colors 
<color name="light_primary_color">#3F51B5</color>
<color name="dark_primary_color">#303f9f</color>

Accent Color
<color name="light_A100">#b388ff</color>
<color name="dark_A700">#aa00ff</color>

**Comment by wp9015362** [comment]
@Etuldan :

Thx for the reply.

So, I assume it's because you personally have a preference for Indigo/Purple/Deep Purple :wink:?

Because those colors have nothing in common with the new logo :stuck_out_tongue: :wink:.

Regards

**Comment by Etuldan** [comment]
Because those colors have nothing in common with the new logo => They have to ?

I'll commit soon with the modifications of colors.
All used colors will be on colors.xml, so it will be easily switchable.

**Comment by wp9015362** [comment]
@Etuldan :

No, they don't have to. I just kinda expected you would go that route because in https://github.com/Etuldan/spaRSS/issues/4 you said:

> it look nice, however, I would like to have some color ( that will probably redefined (see #78 ) and the "feed icon" in it.

But since Orange is pretty much the only color in the new logo and since Orange probably would look worse than Indigo/Purple/Deep Purple as an app color, it's probably just fine that way.

Regards
