### ISSUE TITLE
feed view on startup

### ISSUE THREAD

**Issue by ilf** [Etuldan/spaRSS#8]
Original SparseRSS showed the list of feeds on startup, not the entries in a mixed list. I'd love this back as an option.

**Comment by Etuldan** [comment]
You can have the list (and filter it) by pressing the menu button (top left button).

I'll maybe add a option to display this menu at startup instead of the list, but ATM, low priority

**Comment by Etuldan** [comment]
Available in the experimental branch (no build yet).
