### ISSUE TITLE
one article

### ISSUE THREAD

**Issue by ullahchozta** [Etuldan/spaRSS#80]
hello, i have problem, if i add rss, why just show one article ?

**Comment by Etuldan** [comment]
What is the URL of the RSS feed ?

**Comment by ullahchozta** [comment]
http://www.umi.ac.id/feed/

**Comment by Etuldan** [comment]
I'm unable to reproduce the issue with the url :/

On my device, with the current build I have 10 articles.
What is the "TIme that the entries will be kept" setting you set in spaRSS ? (global and for this feed).
Could you try with a unlimited (or very long) time for this setting ?

**Comment by ullahchozta** [comment]
okey..i can solved that.. thanks
