### ISSUE TITLE
Korean translation still contains the word 'Flym'

### ISSUE THREAD

**Issue by halcyonest** [Etuldan/spaRSS#85]
<?xml version="1.0" encoding="utf-8"?>
<resources>

    
    <string name="app_name">spaRSS</string>
    <string name="about_spaRSS">spaRSS 정보</string>
    <string name="welcome_title">spaRSS 사용을 환영합니다. 피드를 추가하시겠습니까?</string>
    <string name="never">하지 않음</string>
    <string name="update">업데이트</string>
    <string name="colon">:\u00A0</string>
    <string name="menu_settings">설정</string>
    <string name="menu_refresh">새로 고침</string>
    <string name="menu_all_read">모두 읽은 것으로 표시</string>
    <string name="spaRSS_feeds">spaRSS 피드</string>
    <string name="error">오류</string>
    <string name="network_error">네트워크가 준비되지 않았습니다</string>
    <string name="loading">읽어들이는 중…</string>
    <string name="no_result">결과 없음</string>
    <string name="drawer_open">탐색 서랍 열기</string>
    <string name="drawer_close">탐색 서랍 닫기</string>
    <string name="back_again_to_quit">뒤로 가기 버튼을 한번 더 누르면 나갑니다</string>

    
    <string name="feeds">피드</string>
    <string name="menu_add_feed">피드 추가</string>
    <string name="no_feeds">피드 없음</string>
    <string name="no_filters">규칙 없음</string>
    <string name="context_menu_delete">삭제</string>
    <string name="edit_feed_title">피드 편집</string>
    <string name="new_feed_title">새 피드</string>
    <string name="context_menu_edit">편집</string>
    <string name="menu_add_group">그룹 추가</string>
    <string name="menu_import">OPML에서 가져오기</string>
    <string name="menu_export">OPML로 내보내기</string>
    <string name="error_feed_error">피드 주소에 접근할 수 없습니다.</string>
    <string name="error_feed_process">피드를 처리할 수 없습니다.</string>
    <string name="error_feed_url_exists">그 주소는 이미 있습니다.</string>
    <string name="error_feed_import">선택한 파일을 가져올 수 없습니다.</string>
    <string name="error_feed_export">내보내기가 실패했습니다. 쓰기 가능한 SD 카드 저장소가 마운트되어 있는지 확인하십시오.</string>
    <string name="error_external_storage_not_available">외부 저장소(SD 카드 따위)가 없습니다.</string>
    <string name="feed_url">URL 주소</string>
    <string name="optional">(선택 사항)</string>
    <string name="website_or_feed">(웹페이지 또는 피드)</string>
    <string name="tab_feed_title">피드</string>
    <string name="tab_filters_title">필터</string>
    <string name="feed_title">제목</string>
    <string name="feed_filters">필터 규칙</string>
    <string name="filter_add_title">규칙 추가</string>
    <string name="filter_delete_title">규칙 삭제</string>
    <string name="filter_edit_title">규칙 편집</string>
    <string name="filter_is_regex">정규식임</string>
    <string name="filter_apply_to_title">제목에 적용</string>
    <string name="filter_apply_to_content">내용에 적용</string>
    <string name="accept">허용</string>
    <string name="reject">거부</string>
    <string name="feed_search">피드 검색</string>
    <string name="select_file">파일 선택(SD 루트)</string>
    <string name="question_delete_feed">정말로 이 피드를 삭제하시겠습니까?</string>
    <string name="question_delete_group">정말로 이 그룹과 이 안의 피드를 모두 삭제하시겠습니까?</string>
    <string name="question_delete_filter">정말로 이 필터를 삭제하시겠습니까?</string>
    <string name="add_group_title">그룹 이름 선택</string>
    <string name="edit_group_title">그룹 이름 편집</string>
    <string name="message_exported_to">%s에 내보냄</string>
    <string name="to_group_title">피드 옮기기 동작</string>
    <string name="to_group_message">피드를 그룹 안에 넣을 수도 있고 위에 놓을 수도 있습니다. 어떻게 하시겠습니까?</string>
    <string name="to_group_above">그룹 위</string>
    <string name="to_group_into">그룹 안</string>
    <string name="add_custom_feed">임의의 피드를 추가하거나 검색하기</string>
    <string name="google_news_title">구글 뉴스 주제</string>
    <string name="google_news_indicator">추가할 주제를 하나 또는 여러 개를 선택하십시오. 언어에 따라 일부 주제는 Google에서 제공하지 않을 수도 있습니다.</string>
    <string name="google_news_top_stories">주요 뉴스</string>
    <string name="google_news_world">국제</string>
    <string name="google_news_business">경제</string>
    <string name="google_news_technology">기술</string>
    <string name="google_news_entertainment">연예</string>
    <string name="google_news_sports">스포츠</string>
    <string name="google_news_science">과학</string>
    <string name="google_news_health">건강</string>

    
    <string name="all">항목</string>
    <string name="no_entries">항목 없음</string>
    <string name="favorites">별표</string>
    <string name="context_menu_hide_read">읽은 항목 감추기</string>
    <string name="context_menu_show_read">읽은 항목 보이기</string>
    <string name="context_menu_share_starred">별표 항목 공유</string>
    <string name="menu_star">별표</string>
    <string name="menu_unstar">별표 취소</string>
    <string name="menu_share">공유</string>
    <string name="menu_full_screen">전체 화면</string>
    <string name="menu_copy_clipboard">링크 복사</string>
    <string name="menu_mark_as_unread">읽은 것으로 표시</string>
    <string name="share_favorites_title">spaRSS: 별표 항목</string>
    <string name="copied_clipboard">링크 복사함</string>
    <string name="get_full_text">전체 텍스트 가져오기</string>
    <string name="original_text">원래 텍스트 가져오기</string>
    <string name="see_enclosure">내장 미디어 보기</string>
    <string name="see_link">브라우저에서 보기</string>
    <string name="cant_open_link">이 링크에 대한 프로그램이 없습니다</string>
    <string name="open_enclosure">내장 미디어 열기</string>
    <string name="file">파일</string>
    <string name="download_and_save">다운로드 및 저장</string>
    <string name="open_link">링크 열기</string>
    <string name="tip_sentence">팁: 항목을 왼쪽으로 당기면 읽은 항목으로 설정할 수 있고 오른쪽으로 당기면 즐겨찾기로 설정할 수 있습니다</string>

    
    <string name="red">빨강</string>
    <string name="green">녹색</string>
    <string name="blue">파랑</string>
    <string name="transparency">투명도</string>

    
    <string name="settings_category_refresh">자동 새로 고침</string>
    <string name="settings_refresh_enabled">자동 새로 고침 사용</string>
    <string name="settings_refresh_enabled_description">피드 자동 새로 고침 기능을 사용</string>
    <string name="settings_refresh_interval">새로 고침 간격</string>
    <string name="settings_category_notifications">알림</string>
    <string name="settings_notifications_enabled">알림 사용</string>
    <string name="settings_notifications_enabled_description">새 항목에 대한 알림을 사용</string>
    <string name="settings_notifications_ringtone">벨소리</string>
    <string name="settings_notifications_ringtone_none">없음</string>
    <string name="settings_notifications_vibrate">진동</string>
    <string name="settings_notifications_vibrate_description">새 항목이 있을 때 진동 사용</string>
    <string name="settings_notifications_light">LED 알림</string>
    <string name="settings_notifications_light_description">새 항목을 알릴 때 LED 알림 사용</string>
    <string name="settings_category_content_presentation">내용 표시</string>
    <string name="settings_light_theme">밝은 테마</string>
    <string name="settings_light_theme_description">밝은 테마를 사용</string>
    <string name="settings_keep_time">항목을 저장할 시간</string>
    <string name="settings_display_images">이미지 표시</string>
    <string name="settings_display_images_description">항목에서 이미지 표시</string>
    <string name="settings_preload_image_mode">이미지 미리 읽기</string>
    <string name="settings_font_size">글자 크기</string>
    <string name="settings_display_oldest_first">항목 순서</string>
    <string name="settings_display_oldest_first_description">오래된 항목을 먼저 표시</string>
    <string name="settings_display_entries_fullscreen">Auto-fullscreen entries</string>
    <string name="settings_display_entries_fullscreen_description">Automatically display entries in fullscreen</string>
    <string name="settings_refresh_on_open">열면 피드 새로 고침</string>
    <string name="settings_refresh_on_open_description">프로그램을 열면 모든 피드 새로 고침</string>
    <string name="settings_refresh_wifi_only">Wi-Fi에서만 새로 고침</string>
    <string name="settings_refresh_wifi_only_description">Wi-Fi를 사용할 때만 자동으로 새로 고침</string>
    <string name="settings_visible_feeds">피드 모양</string>
    <string name="settings_widget_background">배경</string>
    <string name="settings_widget_background_description">위젯 배경의 색 및 투명도</string>
    <string name="all_feeds">모든 피드(앞으로의 피드 포함)</string>
    <string name="settings_screen_proxy">프록시</string>
    <string name="settings_category_network">네트워크</string>
    <string name="settings_proxy_enabled">사용</string>
    <string name="settings_proxy_wifi_only">Wi-Fi 전용</string>
    <string name="settings_proxy_wifi_only_description">Wi-Fi에서만 프록시 사용</string>
    <string name="settings_proxy_host">호스트</string>
    <string name="settings_proxy_port">포트</string>
    <string name="settings_proxy_type">종류</string>

    <plurals name="number_of_new_entries">
        <item quantity="other">새 항목 %d개</item>
    </plurals>

    <string-array name="settings_intervals">
        <item>1분</item>
        <item>5분</item>
        <item>15분</item>
        <item>30분</item>
        <item>1시간</item>
        <item>2시간</item>
        <item>6시간</item>
        <item>12시간</item>
        <item>1일</item>
    </string-array>
    <string-array name="settings_keep_times">
        <item>1일</item>
        <item>2일</item>
        <item>4일</item>
        <item>1주</item>
        <item>2주</item>
        <item>1달</item>
        <item>2달</item>
        <item>3달</item>
        <item>계속</item>
    </string-array>
    <string-array name="settings_font_sizes">
        <item>-2</item>
        <item>-1</item>
        <item>표준 크기</item>
        <item>+1</item>
        <item>+2</item>
        <item>+3</item>
        <item>+4</item>
        <item>+5</item>
    </string-array>
    <string-array name="settings_preload_image_modes">
        <item>안 함</item>
        <item>Wi-Fi를 통해서만</item>
        <item>언제나</item>
    </string-array>
</resources>

**Comment by halcyonest** [comment]
This is a new translation. Also some strings are not added yet, like

- Left panel
- Display the left panel at startup of the application
- Auto-fullscreen entries
- Automatically display entries in fullscreen
- Display button Mark all as read
- Show / Hide the button (restart required)

**Comment by Etuldan** [comment]
Thanks for the improved/new translation :)
