### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by halcyonest** [Etuldan/spaRSS#86]
I recently switched to spaRSS from semi-discontinued Flym. It will be good if spaRSS can have simple Lollipop style icon. I made a sample icon with free-licence font.

![icon](https://cloud.githubusercontent.com/assets/12594372/10092800/328da1f6-6385-11e5-8e98-191fda03b6f9.png)

*Download ![icon.svg.png](https://cloud.githubusercontent.com/assets/12594372/10093923/47741578-6394-11e5-80a5-2aac02a999f7.png) and remove '.png' extension to get an original SVG file.*

**Comment by Etuldan** [comment]
Thanks for the picture.
However, please use this 'issue' #4 (for exemple, I prefer to not include 'plaintext' in the logo.

**Comment by halcyonest** [comment]
Added heavily stylised S, P and A letters inspired by @arunvikraman.

![icon21](https://cloud.githubusercontent.com/assets/12594372/10097436/fc4c5fea-63b3-11e5-8e31-5cbfd123e12a.png)

- Click ![icon21.svg.png](https://cloud.githubusercontent.com/assets/12594372/10097467/42400c18-63b4-11e5-8ef0-c943fdcea58c.png) to download SVG file (change the extension to SVG)

![icon22](https://cloud.githubusercontent.com/assets/12594372/10097444/0290d994-63b4-11e5-9faa-10a8714aa09f.png)

- Click ![icon22.svg.png](https://cloud.githubusercontent.com/assets/12594372/10097468/42474ba4-63b4-11e5-8f5e-210898b59303.png) to download SVG file (change the extension to SVG)

**Comment by Etuldan** [comment]
Thanks for this work.
I'll probably combine the 2 logos (yours and the @arunvikraman one).
But, unfortunately, I can't download the svg one. (forbidden)

**Comment by Etuldan** [comment]
@halcyonest see https://github.com/Etuldan/spaRSS/issues/4 , I have a last question about you ;)

**Comment by halcyonest** [comment]
Feel free to use or modify this logo, and if there is any better logo just replace it :)

Oh, and I found that widget selection(from homescreen) still displays an old logo.

**Comment by Etuldan** [comment]
About the old logo in widget selection, it may be related to your launcher cache (as there is no more the old icon in the source)

**Comment by GreenLunar** [comment]
I suggest to do this:

Newspaper cover and round Globe/RSS icon above it.

Newspaper cover with title spaRSS as in https://github.com/Etuldan/spaRSS/issues/86#issue-108253539

```
+--------+
| spaRSS |
| ____ ❒ |
| ______ |
| ______ |
| ______ |
+--------+
```

Orange globe icon with semi-transparent RSS curved bars (on center, as in images above or on top-right and smaller)
