### ISSUE TITLE
Full text retrieving error

### ISSUE THREAD

**Issue by arunvikraman** [Etuldan/spaRSS#88]
while retrieving full text from http://www.bdpa.in/feed/ the reader, just pulls in data from "preface" section in the main page, ie http://www.bdpa.in/ and not the actual linked page.

**Comment by Etuldan** [comment]
At the moment, nothing I can do, as the source file (HTML) of an article include also the "preface" (while disabled probably with javascript in a real browser)

Exemple : 
http://www.bdpa.in/pay-anomaliesaberration-on-non-executives-as-well-as-executives/ , line ~350

**Comment by arunvikraman** [comment]
i fixed it using feedsapi full text parser which does a smarter job than SpaRSS html parser in this case...
