### ISSUE TITLE
Unable to get Facebook page feed

### ISSUE THREAD

**Issue by mrfanatic** [Etuldan/spaRSS#9]
Facebook feed format RSS 2.0
https://www.facebook.com/feeds/page.php?format=rss20&id=649188628486342

Still it doesn't get the contents if i burn the above link in Google Feedburner.
Note: Original SparseRSS can read facebook feed.

**Comment by Etuldan** [comment]
I'm able to fix the issue (a HTTP Header redirect was the problem, wrongly detected by spaRSS). It was not related only to Facebook.
However, there is some paging issue about Facebook content.

I'll be able to provide you a pre-release APK that fix only the redirect issue.
I'll work on the paging issue later.

**Comment by mrfanatic** [comment]
Great, thank you.
