### ISSUE TITLE
RssAtomParser.java fix

### ISSUE THREAD

**Issue by darrenaronofsky** [Etuldan/spaRSS#91]
can somebody just give me the two lines codes for RssAtomParser.java that takes out all feeds with text "ERROR:" in it... i know this can be done with filters, but its not practical when you have many feeds with similar issue...@Etuldan @ildar

i dont code, but it should be something like
    <B>RssAtomParser.java</B>
    if (mFeedTitle == null && mTitle != null && mTitle.length() > 0 <B><i>&&!mTitle.contains("ERROR:")</i></B>) {
    mFeedTitle = mTitle.toString();

If somebody uses feed43 (or similar services that does web-scraping to write RSS) for their feeds, they will understand why i have such a weird request here... for others you may need to subscribe to (eg: http://feed43.com/deshabhimaniedu.xml) for a day or two. You get all these errors feeds...  

you can just google around to see many websites using such scraping scripts to create content on the fly. And when subscribing to one of them gives you a nightmare.

![clipboard01](https://cloud.githubusercontent.com/assets/12801410/10122739/250fe320-653f-11e5-819f-4ae996b9d98e.png)

**Comment by Etuldan** [comment]
So, If I understand correctly : 
You add some feeds created by feed43 service, which scrap for content and create a RSS file. If the content is unavailable, feed43 still create a regular RSS file, with "ERROR: [...]" in the title ?

**Comment by darrenaronofsky** [comment]
its not just a feed43 issue... its mostly found in autopilot websites where they use some makerss.php makefull-textfeed.php etc, to generate feeds of sites that dont offer them directly. I have seen issues with websites that use feedsapi, five filters, feed 43 etc..

From what I understand is that these timeouts are generated when their servers from which they scrape is slow to respond.
